### ISSUE TITLE
Question title bar

### ISSUE THREAD

**Issue by progfiles** [neevek/Paginize#10]
Cool framework!
Do you have solution for hide title bar programmaticaly?
What if some pages need full screen?

**Comment by neevek** [comment]
Take a look at the source code of the demo project. Title bar is set by the user of the library, not forced by the library. You can just not include ToolBar in the layout XML.

Paginize tries not to force you to have to work with action bars, you work with full screen by nature.

**Comment by progfiles** [comment]
@neevek I mean what if after splash full screen window other pages need title bar. (Change activity Theme)

**Comment by neevek** [comment]
For real full screen, system bars(status bar and navigation bar) should be taken into account, you can call `getPageActivity()` to get the container activity and change flags for the activity.

If you don't take system bars into account, then Paginize can be used as is to achieve what you want, **you don't change activity themes**. Simply put, use a ToolBar for the splash page, and don't use ToolBar for other pages.

~~It is highly recommended to use Paginize with single Activity for entire app.~~
See [this](https://github.com/neevek/Paginize/issues/11#issuecomment-249400039) for why the above line is striken-out.
