### ISSUE TITLE
Thank you for publishing a good framework.

### ISSUE THREAD

**Issue by handjiny** [neevek/Paginize#13]
I am using it too well.

There is a necessary function in use.
I want to delete the desired page from the record while the sequential page is moving.
To remove b from a-> b-> c and go back to a in c

b.java
   @Override
    public void onCovered() {
        super.onCovered();
        getPageManager().deletePage(0);
    }

Is that right?

If it is correct, I would like deletePage to have the ability to delete the page or page name instead of index

index is difficult to use because there are many variables.

thanks.

**Comment by neevek** [comment]
Page has no name, also it is not recommended to pass page references around and `PageManager` doesn't provide a `delete by page reference` method, so you cannot delete a page either by name or page reference.

You can achieve what you want by enumerating all pages in the stack with `PageManager.getPageCount()` and `PageManager.getPage(index)`, then use `instanceof` or whatever methods that you see fit to find the page you wanted to delete, and delete it by index.

**Comment by handjiny** [comment]
Okay. Thanks for the comment.
