### ISSUE TITLE
Layout from java / Anvil usage

### ISSUE THREAD

**Issue by FunnyDevs** [neevek/Paginize#14]
Is possibile to add a layout runtime without using annotations? i want to try Anvil library but with @PageLayout annotation is impossibile.

**Comment by neevek** [comment]
No, currently you cannot call `setContentView` with Paginize. 

I am not familiar with Anvil, but it looks to me that it doesn't require you use `setContentView`, it seems you can still create your `RenderableView` separately, use it in your layout file, and specify your layout with `@PageLayout`. Or maybe you can use `Anvil.mount()`.

**Comment by FunnyDevs** [comment]
Anvil convenience is making screen layout from java code without to write a lot of xml files. I think, therefore, the only solution is to create a single xml layout for all Pages and then use Anvil.mount to mount the RenderableView with real Page layout.
