### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by FunnyDevs** [neevek/Paginize#5]
Hi! Is possible to use different transitions between pages? Because i looked at the code and the pages transition is defined as an Activity annotation

**Comment by neevek** [comment]
Yes, you can implement transition for a specific page by overriding `Page.onPushPageAnimation()`, `Page.onPopPageAnimation()` and `Page.getAnimationDuration()`.

**Comment by FunnyDevs** [comment]
Ok, thanks a lot. I would like to try this library to abandon fragments. I think it might be better if i could use Butterknife.
