### ISSUE TITLE
ViewPagerPage removePage

### ISSUE THREAD

**Issue by FunnyDevs** [neevek/Paginize#7]
Hi! There is a bug when i try to remove all innerpage except the first (i have tried with 3 innerpages): despite i call "removePage", i am able to swipe to the second innerPage but, if i release the touch, viewpager return to the first innerpage.

**Comment by neevek** [comment]
Hi, @FunnyDevs Bug confirmed and fixed.
`ViewPagePage` uses `ViewPager` to achieve paging, and that was a bug of `ViewPager`. I used a solution from [this](http://stackoverflow.com/a/7287121/668963) stackoverflow answer.

**Comment by FunnyDevs** [comment]
Thanks!
