### ISSUE TITLE
lazyInitializeLayout(int) method does not work well

### ISSUE THREAD

**Issue by zhangxg910** [neevek/Paginize#8]
Hi, neevek
Long time no see, I have find a bug in Paginize lib, please fix it, here are the bug description.

public abstract class APage extends Page {

```
@InjectView(value = R.id.xxx, lazy = true)
protected View mView;

public APage(PageActivity context) {
    View view = lazyInitializeLayout(R.layout.xxx);

    //do extra work
}

protected abstract void doSomething();
```

}

public class BPage extends APage {

```
protected void doSomething() {
    //do something here
}
```

}

public class CPage extends APage {

```
protected void doSomething() {
    //do something here
}
```

}

when create BPage or CPage Object, the field mView is still null, here is my resolution in ViewWrapper.java

```
/**
* inject views after the ViewWrapper is constructed
*/
protected View lazyInitializeLayout(int layoutResId) {
    final View view = mContext.getLayoutInflater().inflate(layoutResId, null, false);
    ViewFinder viewFinder = new ViewFinder() {
      public View findViewById(int id) {
        return view.findViewById(id);
      }
    };

    StackTraceElement[] traces = Thread.currentThread().getStackTrace();

    try {

        Class<?> clazz = null;
        String className;
        String viewWrapperClassName = ViewWrapper.class.getName();
        for (StackTraceElement trace : traces) {
            className = trace.getClassName();
            if (viewWrapperClassName.equals(className)) {
                continue;
            }

            Class<?> cls = Class.forName(className);
            if (ViewWrapper.class.isAssignableFrom(cls)) {
                clazz = cls;
                break;
            }
        }

        if (clazz != null) {
            AnnotationUtils.initAnnotatedFields(clazz, this, viewFinder, true);
            AnnotationUtils.handleAnnotatedConstructors(clazz, this, viewFinder, true);
        } else {
            //usually it can not be run here
            AnnotationUtils.initAnnotatedFields(getClass(), this, viewFinder, true);
            AnnotationUtils.handleAnnotatedConstructors(getClass(), this, viewFinder, true);
        }

    } catch (Exception e) {
      e.printStackTrace();
      throw new InjectFailedException(e);
    }

    return view;
}
```

**Comment by neevek** [comment]
Hi @zhangxg910 
The bug was confirmed and I think the solution is acceptable. Do you mind submitting a pull request for fixing this bug?
It'd be better you format the code with 2-space indents, put the `getStackTrace()` call inside the `try` block, and remove unnecessary blank lines.

Thanks.

**Comment by zhangxg910** [comment]
It seems no available permission for me at the moment while I try to push the code to github, it promped the info "remote: Permission neevk/Paginize.git denied to zhangxg910, fatal: unable to access 'https://github.com/neevek/Paginize.git/' : The requested URL retuened error: 403". Can you do a favor for me to fix it?

**Comment by neevek** [comment]
Hi @zhangxg910 
You will have  to fork the repo and push to your own fork, then submit your PR through your own fork.

Take a look at [this](https://help.github.com/articles/fork-a-repo/) for how to fork a repo and [this](https://help.github.com/articles/using-pull-requests/) for how to submit a PR.

**Comment by zhangxg910** [comment]
Got it

**Comment by neevek** [comment]
Hi @zhangxg910
